[redhat] add dwarves to the list of deps for SRPM generation
Add dwarves as requirement for the .config generation, as it contains
pahole, which since about one week is required to generate proper config
files in -next when debug packages are enabled. Otherwise
CONFIG_DEBUG_INFO_BTF might be disabled and then the build will fail
when bpftool is used to generate $RPM_BUILD_ROOT/$DevelDir/vmlinux.h:

 + tools/bpf/bpftool/bootstrap/bpftool btf dump file vmlinux format c
 libbpf: failed to find '.BTF' ELF section in vmlinux
 Error: failed to load BTF from vmlinux: No data available
 error: Bad exit status from /var/tmp/rpm-tmp.rRU7jN (%build)

Signed-off-by: Thorsten Leemhuis <fedora@leemhuis.info>