net: ethernet: ti: Makefile: Add icssg_queues.o in TI_ICSSG_PRUETH_SR1
icssg_config.c uses some APIs that are defined in icssg_queue.c.
TI_ICSSG_PRUETH_SR1 uses icssg_config.o but not icssg_queues.o as a
result the below build error is seen

ERROR: modpost: "icssg_queue_pop"
[drivers/net/ethernet/ti/icssg-prueth-sr1.ko] undefined!
ERROR: modpost: "icssg_queue_push"
[drivers/net/ethernet/ti/icssg-prueth-sr1.ko] undefined!

Fix this by adding icssg_queues.o in TI_ICSSG_PRUETH_SR1

Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202405182038.ncf1mL7Z-lkp@intel.com/
Fixes: 487f7323f39a ("net: ti: icssg-prueth: Add helper functions to configure FDB")
Signed-off-by: MD Danish Anwar <danishanwar@ti.com>